window.NC_QUESTIONS = [
  { id:'contains-duplicate', title:'Contains Duplicate', category:'Arrays & Hashing', difficulty:'Easy', link:'https://leetcode.com/problems/contains-duplicate/', signature:'containsDuplicate(nums)', starter:'function containsDuplicate(nums) {\n  // TODO: return true when any value appears at least twice\n}\nreturn containsDuplicate(event.nums);', tests:[{input:{nums:[1,2,3,1]}, expected:true},{input:{nums:[1,2,3,4]}, expected:false},{input:{nums:[1,1,1,3,3,4,3,2,4,2]}, expected:true}] },
  { id:'valid-anagram', title:'Valid Anagram', category:'Arrays & Hashing', difficulty:'Easy', link:'https://leetcode.com/problems/valid-anagram/', signature:'isAnagram(s, t)', starter:'function isAnagram(s, t) {\n  // TODO: compare character frequencies\n}\nreturn isAnagram(event.s, event.t);', tests:[{input:{s:'anagram',t:'nagaram'}, expected:true},{input:{s:'rat',t:'car'}, expected:false}] },
  { id:'two-sum', title:'Two Sum', category:'Arrays & Hashing', difficulty:'Easy', link:'https://leetcode.com/problems/two-sum/', signature:'twoSum(nums, target)', starter:'function twoSum(nums, target) {\n  // TODO: return indices of two numbers that add to target\n}\nreturn twoSum(event.nums, event.target);', tests:[{input:{nums:[2,7,11,15],target:9}, expected:[0,1]},{input:{nums:[3,2,4],target:6}, expected:[1,2]}] },
  { id:'valid-palindrome', title:'Valid Palindrome', category:'Two Pointers', difficulty:'Easy', link:'https://leetcode.com/problems/valid-palindrome/', signature:'isPalindrome(s)', starter:'function isPalindrome(s) {\n  // TODO: ignore punctuation, spaces, and case\n}\nreturn isPalindrome(event.s);', tests:[{input:{s:'A man, a plan, a canal: Panama'}, expected:true},{input:{s:'race a car'}, expected:false}] },
  { id:'best-time-to-buy-and-sell-stock', title:'Best Time to Buy and Sell Stock', category:'Sliding Window', difficulty:'Easy', link:'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/', signature:'maxProfit(prices)', starter:'function maxProfit(prices) {\n  // TODO: maximize one buy/sell transaction\n}\nreturn maxProfit(event.prices);', tests:[{input:{prices:[7,1,5,3,6,4]}, expected:5},{input:{prices:[7,6,4,3,1]}, expected:0}] },
  { id:'valid-parentheses', title:'Valid Parentheses', category:'Stack', difficulty:'Easy', link:'https://leetcode.com/problems/valid-parentheses/', signature:'isValid(s)', starter:'function isValid(s) {\n  // TODO: use a stack for brackets\n}\nreturn isValid(event.s);', tests:[{input:{s:'()[]{}'}, expected:true},{input:{s:'(]'}, expected:false},{input:{s:'([)]'}, expected:false}] },
  { id:'binary-search', title:'Binary Search', category:'Binary Search', difficulty:'Easy', link:'https://leetcode.com/problems/binary-search/', signature:'search(nums, target)', starter:'function search(nums, target) {\n  // TODO: return target index or -1\n}\nreturn search(event.nums, event.target);', tests:[{input:{nums:[-1,0,3,5,9,12],target:9}, expected:4},{input:{nums:[-1,0,3,5,9,12],target:2}, expected:-1}] },
  { id:'invert-binary-tree', title:'Invert Binary Tree', category:'Trees', difficulty:'Easy', link:'https://leetcode.com/problems/invert-binary-tree/', signature:'invertTree(root)', starter:'function invertTree(root) {\n  // TODO: swap left and right children recursively or iteratively\n}\nreturn invertTree(event.root);', tests:[{input:{root:{val:2,left:{val:1},right:{val:3}}}, expected:{val:2,left:{val:3},right:{val:1}}}] },
  { id:'number-of-islands', title:'Number of Islands', category:'Graphs', difficulty:'Medium', link:'https://leetcode.com/problems/number-of-islands/', signature:'numIslands(grid)', starter:'function numIslands(grid) {\n  // TODO: count connected land components\n}\nreturn numIslands(event.grid);', tests:[{input:{grid:[["1","1","0"],["1","0","0"],["0","0","1"]]}, expected:2}] },
  { id:'climbing-stairs', title:'Climbing Stairs', category:'1-D Dynamic Programming', difficulty:'Easy', link:'https://leetcode.com/problems/climbing-stairs/', signature:'climbStairs(n)', starter:'function climbStairs(n) {\n  // TODO: fibonacci-style count\n}\nreturn climbStairs(event.n);', tests:[{input:{n:2}, expected:2},{input:{n:3}, expected:3},{input:{n:5}, expected:8}] },
  { id:'coin-change', title:'Coin Change', category:'1-D Dynamic Programming', difficulty:'Medium', link:'https://leetcode.com/problems/coin-change/', signature:'coinChange(coins, amount)', starter:'function coinChange(coins, amount) {\n  // TODO: minimum coins or -1\n}\nreturn coinChange(event.coins, event.amount);', tests:[{input:{coins:[1,2,5],amount:11}, expected:3},{input:{coins:[2],amount:3}, expected:-1}] },
  { id:'merge-intervals', title:'Merge Intervals', category:'Intervals', difficulty:'Medium', link:'https://leetcode.com/problems/merge-intervals/', signature:'merge(intervals)', starter:'function merge(intervals) {\n  // TODO: combine overlapping ranges\n}\nreturn merge(event.intervals);', tests:[{input:{intervals:[[1,3],[2,6],[8,10],[15,18]]}, expected:[[1,6],[8,10],[15,18]]}] }
];
